﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Movement_API
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"TypeUtilisateur", @"TypeUtilisateur"),new InputOutputColumnPair(@"LongitudeBorneDepart", @"LongitudeBorneDepart"),new InputOutputColumnPair(@"LongitudeBorneArrivee", @"LongitudeBorneArrivee"),new InputOutputColumnPair(@"LatitudeBorneDepart", @"LatitudeBorneDepart"),new InputOutputColumnPair(@"LatitudeBorneArrivee", @"LatitudeBorneArrivee")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Date", @"Date"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"TypeUtilisateur",@"LongitudeBorneDepart",@"LongitudeBorneArrivee",@"LatitudeBorneDepart",@"LatitudeBorneArrivee",@"Date"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=25,MinimumExampleCountPerLeaf=8,NumberOfIterations=30,MaximumBinCountPerFeature=884,LearningRate=0.614362341356769F,LabelColumnName=@"DureeEnSecondes",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.83598178216964F,FeatureFraction=1F,L1Regularization=0.0246702055312213F,L2Regularization=0.000584974916739539F}}));

            return pipeline;
        }
    }
}
